---
apiVersion: v1
kind: Service
metadata:
  name: testapp
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
  labels:
    app: testapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: my-blazor-image
        # image: us-central1-docker.pkg.dev/GOOGLE_PROJECT/demo/nginx:latest
        image: europe-west3-docker.pkg.dev/PROJECT_ID/samples/my-blazor-image:latest"