---
apiVersion: v1
kind: Service
metadata:
  name: blazor-deployment
spec:
  type: LoadBalancer
  selector:
    app: blazor-deployment
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazor-deployment
  labels:
    app: blazor-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blazor-deployment
  template:
    metadata:
      labels:
        app: blazor-deployment
    spec:
      containers:
      - name: my-blazor-image
        image: europe-west3-docker.pkg.dev/PROJECT_ID/samples/my-blazor-image:MY_TAG
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"